spring.application.name=usuario-service

server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/db_usuarios?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.liquibase.enabled=true
spring.jpa.hibernate.ddl-auto=none
logging.file.name=logs/usuario-service.log
logging.level.root=INFO
logging.level.com.usuarios=DEBUG