spring.application.name=peliculas-service
server.port=8084

spring.datasource.url=jdbc:mysql://localhost:3306/db_peliculas?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml

spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss

logging.file.name=logs/peliculas-service.log
logging.level.root=INFO
logging.level.com.peliculas=DEBUG
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html