server:
  port: 9090  # EL PUERTO GATEWAY SHAN SHAN SHANN

spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        #Microservicio de usuarios
        - id: usuarios-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/usuarios/**
          
          
        # Microservicio de peliculas
        - id: peliculas-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/peliculas/**, /api/generos/**
        
        # Microservicio de salas
        - id: salas-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/salas/**

        
        - id: funciones-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/funciones/**

        - id: reservas-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/reservas/**