server:
  port: 9090

spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: usuarios-service
          uri: http://usuario-service:8081
          predicates:
            - Path=/api/usuarios/**
          
        - id: peliculas-service
          uri: http://peliculas-service:8084
          predicates:
            - Path=/api/peliculas/**, /api/generos/**
        
        - id: salas-service
          uri: http://sala-service:8083
          predicates:
            - Path=/api/salas/**

        - id: funciones-service
          uri: http://cinefunciones-service:8082
          predicates:
            - Path=/api/funciones/**

        - id: reservas-service
          uri: http://reservas-service:8085
          predicates:
            - Path=/api/reservas/**

        - id: pagos-service
          uri: http://pagos-service:8086
          predicates:
            - Path=/api/pagos/**

        - id: producto-service
          uri: http://producto-service:8087
          predicates:
            - Path=/api/productos/**